########################################
# DATABASE (MySQL)
########################################
spring.datasource.url=jdbc:mysql://172.31.0.1:3306/music_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=Park2508**
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


########################################
# JPA / Hibernate
########################################
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


########################################
# JWT Secret Key
########################################
jwt.secret.key=my-ultra-secure-and-long-secret-key-2025-11


########################################
# SPOTIFY API
########################################
spotify.client.id=b35e2451d3e04d32ab7b9c445090c454
spotify.client.secret=1c7034ff528045358cd176480a462fac
spotify.api-url=https://api.spotify.com/v1
spotify.api.token.url=https://accounts.spotify.com/api/token


########################################
# YOUTUBE API
########################################
youtube.api.key=AIzaSyAe_RW1kyxQ2hJ9AQf6amSisvClI4ecWqY
youtube.api.max-results=1
